[package]
name = "env-exec-tag"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bincode = { version = "2.0.1", features = ["derive"] }
clap = { version = "4.5.36", features = ["derive"] }
